# Generated by Django 6.0.5 on 2026-06-04 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['name'], 'verbose_name': 'hall', 'verbose_name_plural': 'halls'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'menu item', 'verbose_name_plural': 'menu items'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
        migrations.AlterModelOptions(
            name='restauranttable',
            options={'ordering': ['hall__name', 'number'], 'verbose_name': 'restaurant table', 'verbose_name_plural': 'restaurant tables'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['id'], 'verbose_name': 'working hours', 'verbose_name_plural': 'working hours'},
        ),
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='zone',
            field=models.CharField(max_length=80, verbose_name='zone'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starter', 'Starters'), ('main', 'Main dishes'), ('dessert', 'Desserts'), ('drink', 'Drinks')], max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='image URL'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is available'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(max_length=120, verbose_name='customer name'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.PositiveIntegerField(verbose_name='guests'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.restauranttable', verbose_name='table'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='booking.hall', verbose_name='hall'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='number',
            field=models.PositiveIntegerField(verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='seats',
            field=models.PositiveIntegerField(verbose_name='seats'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='close_time',
            field=models.TimeField(verbose_name='close time'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='day',
            field=models.CharField(max_length=20, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is closed'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='open_time',
            field=models.TimeField(verbose_name='open time'),
        ),
    ]
